# Generated by Django 4.2.2 on 2023-06-17 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meditation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtubepost',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
